const settings = [
    {type: 'config', section: 'ads', text: 'Hide banner to view products - 隱藏橫幅廣告', enable: true},
    {type: 'config', section: 'ads', text: 'Hide buttoned ad - 隱藏底部廣告', enable: true},
    {type: 'config', section: 'ads', text: 'Hide fullscreen ads - 隱藏全屏廣告', enable: true},
    {type: 'config', section: 'ads', text: 'Hide general ads - 隱藏一般廣告', enable: true},
    {type: 'config', section: 'ads', text: 'Hide merchandise banners - 隱藏商品橫幅', enable: true},
    {type: 'config', section: 'ads', text: 'Hide paid content - 隱藏付費內容', enable: true},
    {type: 'config', section: 'ads', text: 'Hide self sponsored card - 隱藏相關產品資訊的贊助廣告', enable: true},
    {type: 'config', section: 'ads', text: 'Hide shopping links in video description - 隱藏影片資訊欄中的購物連結', enable: true},
    {type: 'config', section: 'ads', text: 'Hide video ads - 隱藏影片廣告', enable: true},
    {type: 'config', section: 'ads', text: 'Hide web search result - 隱藏搜尋時來自其他網站的結果', enable: true},
    {type: 'config', section: 'ads', text: 'Hide YouTube Premium promotions - 隱藏 YouTube Premium 促銷廣告', enable: true},
    {type: 'description', section: 'dearrow', text: 'DeArrow 是 YouTube 的瀏覽器插件，用於減少聳人聽聞、誤導性標題和侵略性縮圖。 DeArrow 的工作原理是格式化所有標題，並用特定時間戳的螢幕截圖替換原縮圖。'},
    {type: 'config', section: 'dearrow', text: 'Enable DeArrow thumbnails - 啟用 DeArrow 縮圖替換', enable: false},
    {type: 'config', section: 'dearrow', text: 'Show a toast if API is not available - 當無法連接到 API 時出現提醒', enable: false},
    {type: 'option', section: 'dearrow', text: 'DeArrow API endpoint - DeArrow 的快取節點連結 (別修改，除非你知道在做什麼)', option: 'https://dearrow-thumb.ajay.app/api/v1/getThumbnail'},
    {type: 'config', section: 'dearrow', text: 'Enable still video captures - 啟用靜態影像擷取 (拿影片前/中/後期的影像當封面)', enable: false},
    {type: 'option', section: 'dearrow', text: 'Video time to take the still from - 影像擷取時間點', option: '預設為影片的中間'},
    {type: 'config', section: 'dearrow', text: 'Use fast still captures - 啟用高品質靜態影像擷取', enable: false},
    {type: 'description', section: 'feed', text: '[Filter bar] - 篩選器設定', font: 'h5'},
    {type: 'config', section: 'feed', text: 'Hide in feed - 在首頁隱藏篩選器', enable: false},
    {type: 'config', section: 'feed', text: 'Hide in related video - 在相關影片中隱藏篩選器', enable: false},
    {type: 'config', section: 'feed', text: 'Hide in related video - 在搜尋列中隱藏篩選器', enable: false},
    {type: 'description', section: 'feed', text: 'Hide keyword content - 隱藏特定關鍵字的內容', font: 'h5'},
    {type: 'config', section: 'feed', text: 'Hide home video by keywords - 以關鍵字隱藏首頁的影片', enable: false},
    {type: 'config', section: 'feed', text: 'Hide subscription video by keywords - 以關鍵字隱藏訂閱的影片', enable: false},
    {type: 'config', section: 'feed', text: 'Hide search results by keywords - 以關鍵字隱藏搜尋的影片', enable: false},
    {type: 'description', section: 'feed', text: ''},
    {type: 'config', section: 'feed', text: 'Enable wide search bar - 啟用寬搜尋欄', enable: true},
    {type: 'config', section: 'feed', text: 'Hide album cards - 隱藏專輯資訊卡', enable: true},
    {type: 'config', section: 'feed', text: 'Hide artist cards - 隱藏藝術家資訊卡', enable: true},
    {type: 'config', section: 'feed', text: 'Hide breaking news - 隱藏突發新聞', enable: true},
    {type: 'config', section: 'feed', text: 'Hide community posts - 隱藏社群貼文', enable: false},
    {type: 'config', section: 'feed', text: 'Hide compact banners - 隱藏緊湊的橫幅', enable: true},
    {type: 'config', section: 'feed', text: 'Hide crowdfunding box - 隱藏募資資訊', enable: true},
    {type: 'config', section: 'feed', text: 'Hide feed surveys - 隱藏投票', enable: false},
    {type: 'config', section: 'feed', text: 'Hide "For you" shelf in channel page - 隱藏頻道頁面中的「推薦給你」區塊', enable: true},
    {type: 'config', section: 'feed', text: 'Hide image shelf in search results - 在搜尋結果中隱藏縮圖', enable: true},
    {type: 'config', section: 'feed', text: 'Hide latest posts - 隱藏最新貼文', enable: true},
    {type: 'config', section: 'feed', text: 'Hide "Learn More" button - 隱藏「了解更多」按鈕', enable: true},
    {type: 'config', section: 'feed', text: 'Hide mix playlists - 隱藏混合播放清單', enable: true},
    {type: 'config', section: 'feed', text: 'Hide movie section - 隱藏電影區塊', enable: true},
    {type: 'config', section: 'feed', text: 'Hide "Notify me" button - 隱藏「通知我」按鈕', enable: true},
    {type: 'config', section: 'feed', text: 'Hide "People also watched" recommand - 隱藏「其他人也觀看...」的推薦', enable: true},
    {type: 'config', section: 'feed', text: 'Hide search result shelf header - 隱藏搜尋結果標題分組，例如「熱門影片」、「相關播放清單」或「短影音」等', enable: false},
    {type: 'description', section: 'player', text: 'Action buttons - 篩選器設定', font: 'h5'},
    {type: 'config', section: 'player', text: 'Hide Clip - 隱藏「剪輯」按鈕', enable: true},
    {type: 'config', section: 'player', text: 'Hide Download - 隱藏「下載」按鈕', enable: true},
    {type: 'config', section: 'player', text: 'Hide Like and Dislike - 隱藏「喜歡與不喜歡」按鈕', enable: false},
    {type: 'config', section: 'player', text: 'Hide Remix - 隱藏「Remix」按鈕', enable: true},
    {type: 'config', section: 'player', text: 'Hide Report - 隱藏「檢舉」按鈕', enable: true},
    {type: 'config', section: 'player', text: 'Hide Save to playlist - 隱藏「加到播放清單」按鈕', enable: false},
    {type: 'config', section: 'player', text: 'Hide Share - 隱藏「分享」按鈕', enable: false},
    {type: 'config', section: 'player', text: 'Hide Shop - 隱藏「商店」按鈕', enable: true},
    {type: 'config', section: 'player', text: 'Hide Thanks - 隱藏「感謝」按鈕', enable: true},
    {type: 'description', section: 'player', text: 'Comments] - 留言', font: 'h5'},
    {type: 'config', section: 'player', text: 'Hide comments section - 隱藏留言區塊', enable: false},
    {type: 'config', section: 'player', text: 'Hide preview comment - 隱藏留言預覽', enable: false},
    {type: 'description', section: 'player', text: 'External downloads - 外部下載器', font: 'h5'},
    {type: 'config', section: 'player', text: 'Show external download button - 顯示「外部下載」按鈕', enable: false},
    {type: 'config', section: 'player', text: 'Override download action button - 覆蓋下載按鈕(讓「下載」按鈕改使用外部下載器)', enable: false},
    {type: 'option', section: 'player', text: 'download package name - 輸入外部下載器的應用程式ID', option: 'org.schabi.newpipe'},
    {type: 'description', section: 'player', text: 'Flyout menu - 彈出式選單', font: 'h5'},
    {type: 'config', section: 'player', text: 'Hide Additional settings - 隱藏「更多設定」選單', enable: false},
    {type: 'config', section: 'player', text: 'Hide Ambient mode - 隱藏「微光效果模式」', enable: true},
    {type: 'config', section: 'player', text: 'Hide Audio track - 隱藏「音軌」選單', enable: false},
    {type: 'config', section: 'player', text: 'Hide Captions - 隱藏「字幕」選單', enable: false},
    {type: 'config', section: 'player', text: 'Hide Help & feedback - 隱藏「幫助與反饋」選單', enable: true},
    {type: 'config', section: 'player', text: 'Hide Loop video - 隱藏「重複播放影片」選單', enable: false},
    {type: 'config', section: 'player', text: 'Hide More info - 隱藏「更多資訊」選單', enable: true},
    {type: 'config', section: 'player', text: 'Hide Playback speed - 隱藏「播放速度」選單', enable: false},
    {type: 'config', section: 'player', text: 'Hide Report - 隱藏「檢舉」選單', enable: true},
    {type: 'config', section: 'player', text: 'Hide Watch in VR - 隱藏「使用VR觀看」選單', enable: true},
    {type: 'description', section: 'player', text: 'Video description - 影片資訊欄', font: 'h5'},
    {type: 'config', section: 'player', text: 'Hide chapter - 隱藏章節', enable: true},
    {type: 'config', section: 'player', text: 'Hide game section - 隱藏遊戲區塊', enable: true},
    {type: 'config', section: 'player', text: 'Hide info section - 隱藏資訊卡', enable: true},
    {type: 'config', section: 'player', text: 'Hide music section - 隱藏音樂區塊', enable: true},
    {type: 'config', section: 'player', text: 'Hide podcast section - 隱藏 Podcast 區塊', enable: true},
    {type: 'config', section: 'player', text: 'Hide transcript section - 隱藏逐字稿區塊', enable: true},
    {type: 'description', section: 'player', text: ''},
    {type: 'config', section: 'player', text: 'Disable Ambient mode in fullscreen - 在全螢幕下禁用「微光效果模式」', enable: true},
    {type: 'config', section: 'player', text: 'Disable auto captions - 禁用自動字幕', enable: false},
    {type: 'config', section: 'player', text: 'Disable rolling number animations - 禁用數字滾動動畫', enable: false},
    {type: 'config', section: 'player', text: 'Disable suggested video end screen - 禁用結束畫面的建議影片', enable: true},
    {type: 'config', section: 'player', text: 'Hide autoplay button - 隱藏自動播放按鈕', enable: true},
    {type: 'config', section: 'player', text: 'Hide captions button - 隱藏字幕按鈕', enable: false},
    {type: 'config', section: 'player', text: 'Hide cast button - 隱藏投放按鈕', enable: true},
    {type: 'config', section: 'player', text: 'Hide channel bar - 隱藏頻道頂部的資訊列', enable: false},
    {type: 'config', section: 'player', text: 'Hide channel guideline - 隱藏頻道規範', enable: true},
    {type: 'config', section: 'player', text: 'Hide channel member shelf - 隱藏頻道會員區塊', enable: true},
    {type: 'config', section: 'player', text: 'Hide channel watermark - 隱藏頻道浮水印', enable: true},
    {type: 'config', section: 'player', text: 'Hide chips shelf - 隱藏標籤或分類區塊', enable: true},
    {type: 'config', section: 'player', text: 'Hide community guideline - 隱藏社群規範', enable: true},
    {type: 'config', section: 'player', text: 'Hide emergency box - 隱藏緊急通知欄位', enable: true},
    {type: 'config', section: 'player', text: 'Hide end screen cards - 隱藏影片結尾畫面推薦', enable: true},
    {type: 'config', section: 'player', text: 'Hide expandable chips under videos - 隱藏影片下方的可展開標籤', enable: true},
    {type: 'config', section: 'player', text: 'Hide info cards - 隱藏資訊卡', enable: true},
    {type: 'config', section: 'player', text: 'Hide info panels - 隱藏資訊面板', enable: true},
    {type: 'config', section: 'player', text: 'Hide "join" button - 隱藏「加入」按鈕', enable: true},
    {type: 'config', section: 'player', text: 'Hide medical panels - 隱藏醫療面板', enable: true},
    {type: 'config', section: 'player', text: 'Hide player popup panels - 隱藏播放器彈出面板', enable: false},
    {type: 'config', section: 'player', text: 'Hide previous & next video button - 隱藏「上一部影片&下一步影片」按鈕', enable: true},
    {type: 'config', section: 'player', text: 'Hide quick actions in fullscreen - 隱藏全螢幕模式下的快速操作介面', enable: false},
    {type: 'config', section: 'player', text: 'Hide related videos in quick reaction - 隱藏快速操作介面中的相關影片', enable: false},
    {type: 'config', section: 'player', text: 'Hide subscribers community guideline - 隱藏訂閱者社群規範', enable: true},
    {type: 'config', section: 'player', text: 'Hide timed reactions - 隱藏即時反應功能 (❤、💯、🎉...)', enable: true},
    {type: 'option', section: 'player', text: 'Player overlay opacity - 播放器不透明度', option: '0~100, 0為完全透明，100為完全不透明'},
    {type: 'config', section: 'player', text: 'Show copy timestamp URL button - 顯示「複製帶有時間戳的影片連結」按鈕', enable: true},
    {type: 'config', section: 'player', text: 'Show copy video URL button - 顯示「複製影片連結」按鈕', enable: false},
    {type: 'description', section: 'general_layout', text: 'Custom filter - 自訂過濾器', font: 'h5'},
    {type: 'config', section: 'general_layout', text: 'Enable custom filter - 啟用自訂過濾器', enable: false},
    {type: 'option', section: 'general_layout', text: 'Custom filter - 過濾器', option: '條列自訂部件以過濾'},
    {type: 'description', section: 'general_layout', text: 'Navigation button - 導航欄按鈕', font: 'h5'},
    {type: 'config', section: 'general_layout', text: 'Hide home - 隱藏首頁', enable: false},
    {type: 'config', section: 'general_layout', text: 'Hide Shorts - 隱藏 Shorts', enable: true},
    {type: 'config', section: 'general_layout', text: 'Hide Create - 隱藏「建立」', enable: true},
    {type: 'config', section: 'general_layout', text: 'Hide Subscriptions - 隱藏訂閱內容', enable: false},
    {type: 'config', section: 'general_layout', text: 'Switch Create with Notifications - 交換「建立」與「通知」按鈕的位置', enable: false},
    {type: 'description', section: 'general_layout', text: ''},
    {type: 'config', section: 'general_layout', text: 'Enable gradient loading screen - 啟用漸層載入畫面', enable: true},
    {type: 'config', section: 'general_layout', text: 'Enable table layout - 啟用表格佈局', enable: false},
    {type: 'config', section: 'general_layout', text: 'Enable table mini player - 啟用桌面迷你播放器', enable: false},
    {type: 'config', section: 'general_layout', text: 'Hide floating microphone button - 隱藏浮動麥克風按鈕', enable: true},
    {type: 'config', section: 'general_layout', text: 'Hide gray separator - 隱藏灰色分隔符', enable: true},
    {type: 'config', section: 'general_layout', text: 'Remove viewer discretion dialog - 移除觀眾警告對話框 (影片可能包含敏感或不適合所有觀眾的內容...)', enable: true},
    {type: 'option', section: 'general_layout', text: 'Set start page - 設定起始頁面', option: '如探索、訂閱、Shorts、首頁...'},
    {type: 'config', section: 'general_layout', text: 'Spoof app version - 偽造應用程式版本 (用於使用舊版介面)', enable: false},
    {type: 'option', section: 'general_layout', text: 'Spoof app version target - 設定應用程式版本', option: '17.33.42 - 回到舊版 UI 介面'},
    {type: 'config', section: 'shorts', text: 'Disable resuming Shorts player - Shorts 不會在應用程式重啟時恢復播放', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide Shorts in home feed - 在首頁推薦中隱藏 Shorts', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide Shorts in subscription feed - 在訂閱內容中隱藏 Shorts', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide Shorts in search result - 在搜尋內容中隱藏 Shorts', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide like button - 隱藏「喜歡」按鈕', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide remix button - 隱藏「remix」按鈕', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide sound button - 隱藏「音效」按鈕', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide thanks button - 隱藏「感謝」按鈕', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide join button - 隱藏「加入」按鈕', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide subscribe button - 隱藏「訂閱」按鈕', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide subscribe button when paused - 在暫停時隱藏「訂閱」按鈕', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide channel bar - 隱藏頻道資訊列', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide info panel - 隱藏資訊面板', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide full video link label - 隱藏「完整影片連結」標籤', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide Shorts video title - 隱藏 Shorts 影片標題', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide sound metadata label - 隱藏音效元數據標籤', enable: true},
    {type: 'config', section: 'shorts', text: 'Hide navigation bar - 隱藏導航欄', enable: true},
    {type: 'config', section: 'seekbar', text: 'Disable precise seeking gesture - 禁用精確尋找手勢 (進度條上即時預覽)', enable: true},
    {type: 'config', section: 'seekbar', text: 'Hide seekbar in video player - 在影片播放器中隱藏進度條', enable: false},
    {type: 'config', section: 'seekbar', text: 'Hide seekbar in video thumbnails - 在影片縮圖中隱藏進度條', enable: false},
    {type: 'config', section: 'seekbar', text: 'Hide video timestamp - 隱藏影片時間戳', enable: false},
    {type: 'config', section: 'seekbar', text: 'Restore old seekbar thumbnails - 恢復舊版進度條縮圖 (舊版小圖/新版全屏)', enable: true},
    {type: 'config', section: 'seekbar', text: 'Enable seekbar tapping - 啟用進度條點擊', enable: true},
    {type: 'config', section: 'seekbar', text: 'Enable custom seekbar color - 啟用自訂進度條顏色', enable: false},
    {type: 'option', section: 'seekbar', text: 'Custom seekbar color - 自訂進度條顏色', option: '16 進位色碼，如：#FF0000'},
    {type: 'config', section: 'swipe', text: 'Enable brightness gesture - 啟用亮度滑動調整', enable: false},
    {type: 'config', section: 'swipe', text: 'Enable volume gesture - 啟用音量滑動調整', enable: false},
    {type: 'config', section: 'swipe', text: 'Enable press-to-swipe gesture - 啟用按下滑動', enable: false},
    {type: 'config', section: 'swipe', text: 'Enable haptic feedback - 啟用觸覺反饋 (震動)', enable: false},
    {type: 'config', section: 'swipe', text: 'Save and restore brightness - 當離開/進入全屏時，保存/恢復亮度', enable: false},
    {type: 'option', section: 'swipe', text: 'Swipe overlay timeout - 滑動提示顯示持續時間', option: '預設 500 毫秒'},
    {type: 'option', section: 'swipe', text: 'Swipe overlay text size - 滑動提示顯示字體大小', option: '預設 22'},
    {type: 'option', section: 'swipe', text: 'Swipe background visibility - 滑動提示顯示可見度', option: '預設 127'},
    {type: 'option', section: 'swipe', text: 'Swipe magnitude threshold - 滑動判定最小閾值', option: '預設 30'},
    {type: 'config', section: 'dislike', text: 'Return YouTube Dislike - 啟用倒讚數顯示', enable: true},
    {type: 'config', section: 'dislike', text: 'Return dislike in Shorts - 在 Shorts 中啟用倒讚數顯示', enable: true},
    {type: 'config', section: 'dislike', text: 'Dislike as percentage - 以百分比顯示倒讚數', enable: false},
    {type: 'config', section: 'dislike', text: 'Compact like button - 緊湊型按鈕', enable: false},
    {type: 'config', section: 'dislike', text: 'Show a toast if API is not available - 如果 API 無法使用顯示提示', enable: true},
    {type: 'description', section: 'sponsorblock', text: 'SponsorBlock是一個免費且開源的瀏覽器擴展外掛程式，旨在跳過YouTube影片中的贊助片段。該擴展外掛程式依靠使用者提交的資料庫資料來識別影片中的讚助片段。擴展外掛程式的使用者可以提交影片中的片段，並對其他人提交的片段進行投票。'},
    {type: 'config', section: 'sponsorblock', text: 'Enable SponsorBlock - 啟用 SponsorBlock', enable: true},
    {type: 'config', section: 'sponsorblock', text: 'Show voting button - 顯示投票按鈕', enable: false},
    {type: 'config', section: 'sponsorblock', text: 'Use compact skip button - 使用緊湊的跳過按鈕 (跳過按鈕的寬度縮小)', enable: false},
    {type: 'config', section: 'sponsorblock', text: 'Automatically hide skip button - 幾秒後自訂隱藏跳過按鈕', enable: true},
    {type: 'config', section: 'sponsorblock', text: 'Show a toast when skip automatically - 自動跳過後顯示提示', enable: true},
    {type: 'config', section: 'sponsorblock', text: 'Show video length without segments - 顯示扣除跳過片段的影片時長', enable: true},
    {type: 'description', section: 'sponsorblock', text: 'Change segment behavior - 設定對各類型片段的處理方式', font: 'h5'},
    {type: 'description', section: 'sponsorblock', text: '每種片段類型都有五種處理方式： [Skip automatically 自動跳過]、[Skip automatically once 自動跳過一次]、[Show a skip button 顯示跳過按鈕]、[Show in seek bar 在進度條用顏色標記] 和 [Disable 不啟用]。'},
    {type: 'option', section: 'sponsorblock', text: 'Sponsor - 贊助廣告', option: '顯示跳過按鈕'},
    {type: 'option', section: 'sponsorblock', text: 'Unpaid/Self Promotion - 非付費/自我推廣', option: '顯示跳過按鈕'},
    {type: 'option', section: 'sponsorblock', text: 'Interaction Reminder - 互動提醒 (訂閱)', option: '顯示跳過按鈕'},
    {type: 'option', section: 'sponsorblock', text: 'Highlight - 重點 (大部分的人在影片尋找的部分)', option: '在進度條用顏色標記'},
    {type: 'option', section: 'sponsorblock', text: 'Intermission/Intro Animation - 中場休息/開頭動畫', option: '顯示跳過按鈕'},
    {type: 'option', section: 'sponsorblock', text: 'Endcards/Credits - 結束畫面/鳴謝', option: '顯示跳過按鈕'},
    {type: 'option', section: 'sponsorblock', text: 'Preview/Recap/Hook - 預覽 / 回顧 / 摘要節錄', option: '顯示跳過按鈕'},
    {type: 'option', section: 'sponsorblock', text: 'Filler Tangent/Jokes - 離題閒聊/玩笑', option: '不啟用'},
    {type: 'option', section: 'sponsorblock', text: 'Non-Music Section - 非音樂部分 (僅供音樂影片使用)', option: '自動跳過'},
    {type: 'description', section: 'sponsorblock', text: 'Create new segment - 新增新片段', font: 'h5'},
    {type: 'config', section: 'sponsorblock', text: 'Show create new segment button - 顯示新增片段的按鈕', enable: false},
    {type: 'option', section: 'sponsorblock', text: 'Adjust new segment step - 微調片段位置偏移量', option: '150 毫秒'},
    {type: 'description', section: 'sponsorblock', text: 'General - 一般設定', font: 'h5'},
    {type: 'config', section: 'sponsorblock', text: 'Show a toast if API is not available - 如果 API 無法使用顯示提示', enable: false},
    {type: 'config', section: 'sponsorblock', text: 'Enable skip count tracking - 啟用跳過次數紀錄', enable: true},
    {type: 'option', section: 'sponsorblock', text: 'Minimum segment duration - 最小片段秒數 (太短會無視)', option: '0.0 秒'},
    {type: 'option', section: 'sponsorblock', text: 'Your private user id - 你的私人ID', option: ' '},
    {type: 'option', section: 'sponsorblock', text: 'Change API URL - 改變 API 位置', option: 'https://sponsor.ajay.app'},
    {type: 'option', section: 'sponsorblock', text: 'Import/Export setting - 匯入/匯出設定', option: ' '},
    {type: 'description', section: 'misc', text: 'Debugging - 除錯', font: 'h5'},
    {type: 'config', section: 'misc', text: 'Debug logging - 除錯紀錄', enable: false},
    {type: 'config', section: 'misc', text: 'Log protocol buffer - 日誌協定暫存區', enable: false},
    {type: 'config', section: 'misc', text: 'Log stack traces - 日誌堆疊追蹤', enable: false},
    {type: 'config', section: 'misc', text: 'Show toast on ReVanced error - ReVanced 發生錯誤時顯示提示', enable: false},
    {type: 'config', section: 'misc', text: 'Bypass URL redirects - 網頁連結繞過 YouTube 重定向', enable: true},
    {type: 'config', section: 'misc', text: 'Disable zoom haptics - 禁用縮放觸覺反饋 (震動)', enable: true},
    {type: 'config', section: 'misc', text: 'Enable auto repeat - 啟用自動重播', enable: false},
    {type: 'option', section: 'misc', text: 'Import/Export - 匯入/匯出 ReVanced 設定', option: '不含插件設定'},
    {type: 'config', section: 'misc', text: 'Open link in browser - 用瀏覽器開啟連結', enable: true},
    {type: 'config', section: 'misc', text: 'Remove tracking query parameter - 移除連結中用於追蹤的參數', enable: true},
    {type: 'config', section: 'misc', text: 'Show ReVanced announcements - 如果 ReVanced 有公告，在啟動時顯示', enable: true},
    {type: 'config', section: 'misc', text: 'Spoof device dimensions - 偽造設備尺寸 (可解鎖更高畫質，但可能有未知的副作用)', enable: false},
    {type: 'option', section: 'video', text: 'Custom playback speeds - 自訂播放速度', option: '目前可以從 0.25 ~ 5'},
    {type: 'option', section: 'video', text: 'Default playback speed - 預設播放速度', option: '1.0x'},
    {type: 'option', section: 'video', text: 'Default video quality on mobile network - 在行動網路上預設播放畫質', option: '144p'},
    {type: 'option', section: 'video', text: 'Default video quality on Wi-Fi network - 在 Wi-Fi 上預設播放畫質', option: '720p'},
    {type: 'config', section: 'video', text: 'Hide video quality menu footer - 隱藏影片畫質選單', enable: true},
    {type: 'config', section: 'video', text: 'Remember playback speed change - 記得播放速度的更改', enable: false},
    {type: 'config', section: 'video', text: 'Remember video quality change - 記得影片畫質的更改', enable: true},
    {type: 'config', section: 'video', text: 'Restore old video quality menu - 恢復舊版畫質選單', enable: true},
];


const config_template = document.getElementById('config').content;
function insertConfig(containerId, config, index) {
    const container = document.getElementById(containerId);
    const clone = document.importNode(config_template, true);
    const uniqueId = `config${index}`;
    const input = clone.querySelector('input');
    const label = clone.querySelector('label');
    input.id = uniqueId;
    label.setAttribute('for', uniqueId);
    label.textContent = config.text;
    input.checked = config.enable;
    container.appendChild(clone);
}

const option_template = document.getElementById('options').content;
function insertOption(containerId, config) {
    const container = document.getElementById(containerId);
    const clone = document.importNode(option_template, true);
    const label = clone.querySelector('label');
    const option = clone.querySelector('option');
    label.textContent = config.text;
    option.textContent = config.option;
    container.appendChild(clone);
}

function insertDescription(containerId, config) {
    const container = document.getElementById(containerId);
    const clone = document.createElement(config.font||'p');
    clone.className = 'mt-4';
    clone.textContent = config.text;
    container.appendChild(clone);
}

function init() {
    let counter = 0;
    settings.forEach(config => {
        if (config.type === 'config') insertConfig(config.section, config, counter++);
        if (config.type === 'description') insertDescription(config.section, config);
        if (config.type === 'option') insertOption(config.section, config);
    });
}

init();